apiVersion: v2
name: mlbuffet
description: MLBuffet is a Machine Learning model-server that allows model storage, version control, training, and inference. Developed by Zylk.net

home: https://github.com/zylklab/mlbuffet

type: application

version: 1.0.0

icon: https://raw.githubusercontent.com/zylklab/mlbuffet/master/docs/images/MlBuffet_daemon.png

source: 
  - https://github.com/zylklab/mlbuffet

maintainers:
  - name: LaManoServida
    url: https://github.com/LaManoServida
  - name: AlfonsoGonz
    url: https://github.com/AlfonsoGonz
  - name: sergiomhmh
    url: https://github.com/sergiomhmh
  - name: koishus
    url: https://github.com/koishus
  - name: ruben-naranjo
    url: https://github.com/ruben-naranjo