apiVersion: v1
kind: Service
metadata:
  name: inferrer
  namespace: mlbuffet
spec:
  selector:
    app: mlbuffet_inferrer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
