apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: mlbuffet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlbuffet_cache
  template:
    metadata:
      labels:
        app: mlbuffet_cache
    spec:
      containers:
        - name: cache
          image: docker.io/library/mlbuffet_cache:arm64
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: mlbuffet
spec:
  selector:
    app: mlbuffet_cache
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
