apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: mlbuffet
spec:
  selector:
    app: mlbuffet_metrics
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: NodePort
