apiVersion: v1
kind: Service
metadata:
  name: modelhost
  namespace: mlbuffet
spec:
  selector:
    app: mlbuffet_modelhost
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
  internalTrafficPolicy: Cluster
