apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: mlbuffet
spec:
  selector:
    app: mlbuffet_storage
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
