apiVersion: {{ .Values.apiVersion.deployment }}
kind: Deployment
metadata:
  name: {{ .Values.cache.name}}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{.Values.namespace.name}}_{{ .Values.cache.name}}
spec:
  replicas: {{ .Values.cache.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.namespace.name}}_{{ .Values.cache.name}}
  template:
    metadata:
      labels:
        app: {{.Values.namespace.name}}_{{ .Values.cache.name }}
    spec:
      containers:
        - name: {{ .Values.cache.name}}
          image: {{ .Values.images.cache}}
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
          ports:
            - containerPort: 6379

---
apiVersion: {{ .Values.apiVersion.service }}
kind: Service
metadata:
  name: {{ .Values.cache.name}}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{.Values.namespace.name}}_{{ .Values.cache.name}}
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
