apiVersion: {{ .Values.apiVersion.deployment }}
kind: Deployment
metadata:
  name: {{ .Values.inferrer.name}}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{.Values.namespace.name}}_{{ .Values.inferrer.name }}
spec:
  replicas: {{ .Values.inferrer.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.namespace.name}}_{{ .Values.inferrer.name}}
  template:
    metadata:
      labels:
        app: {{.Values.namespace.name}}_{{ .Values.inferrer.name }}
    spec:
     serviceAccountName: {{ .Values.serviceAccount.scheduler.name }}
     containers:
        - name: {{ .Values.inferrer.name}}
          image: {{ .Values.images.inferrer}}
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: ORCHESTRATOR
              value: {{ .Values.orchestratorType | quote}}
            - name: IMAGE_MLBUFFET_TRAINER
              value: {{ .Values.images.trainer}}
            - name: IMAGE_MLBUFFET_MODELHOST
              value: {{ .Values.images.modelhost}}

---

apiVersion: {{ .Values.apiVersion.service }}
kind: Service
metadata:
  name: {{ .Values.inferrer.name}}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{.Values.namespace.name}}_{{ .Values.inferrer.name}}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    {{- if eq $.Values.inferrer.service.type "NodePort"}}
    nodePort: {{ .Values.inferrer.service.nodePort }}
    {{- end }}
  type: {{ .Values.inferrer.service.type }}

