apiVersion: {{ .Values.apiVersion.deployment }}
kind: Deployment
metadata:
  name: {{ .Values.storage.name}}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{.Values.namespace.name}}_{{ .Values.storage.name }}
spec:
  replicas: {{ .Values.storage.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.namespace.name}}_{{ .Values.storage.name}}
  template:
    metadata:
      labels:
        app: {{.Values.namespace.name}}_{{ .Values.storage.name }}
    spec:
      containers:
        - name: {{ .Values.storage.name}}
          image: {{ .Values.images.storage }}
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
          ports:
            - containerPort: 8000

              
---

apiVersion: {{ .Values.apiVersion.service }}
kind: Service
metadata:
  name: {{ .Values.storage.name}}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{.Values.namespace.name}}_{{ .Values.storage.name}}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

